### ISSUE TITLE
Menampilkan Data Dosen

### ISSUE THREAD

**Issue by faisaladi09** [faisaladi1990z/proyek-web-nim-2020#2]
Buatlah data Dosen dan push ke branch .

id_Dosen
name_Dosen
ktp_Dosen
alamat_Dosen
notlp_Dosen
bidang_Dosen
jadwal_Dosen

**Comment by feriksetiawan18** [comment]
tugas anda sudah selesai

**Comment by faisaladi09** [comment]
Baik Terimakasih .
